### PR TITLE
#135 Conan package support

### LINKED ISSUE #135: Conan Package Support
Hello,

Do you know about [Conan](https://conan.io)?

Conan is modern dependency and package manager for C/C++. And would be great if your library would be available via package manager for other developers.

All Conan packages are available on [Conan Center](https://bintray.com/conan/conan-center), where is possible search, install and upload any official Conan package.

As your project uses libuv, we already have such dependency solved by Conan. So you are able to run uvw with libuv pre-built.

We could support you writing a recipe and publishing your packages on Bintray.

If you have any questions, just ask :-)

Regards!

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR brings the support for Conan.

Including:
- .conan/build.py
  Build script to create Conan package on Travis CI
- .conan/test_package/CMakeLists.txt
  CMake file to build test package
- .conan/test_package/conanfile.py
  Conan recipe to build test package
- .conan/test_package/test_package.cpp
  Example code to consume Conan package created
- .travis.yml
  Update to run Conan job on CI
- conanfile.py
  Conan recipe to provide UVM package
- bintray badge on README
  Download link page for UVM package

Conan uses the file *conanfile.py* as recipe to execute all steps necessary to create the package. As your project is header-only it doesn't need build anything, just copy all headers and license. Conan defines the package id by settings + options and UVW is header-only so it doesn't need set anything.

To make sure that your package is working well, Conan provides test_package, where we put a simple example consuming your package and building as well. When test_package.cpp is including uvw header, all files are imported from the packaged provided by Conan. Test package is not for unit testing propose, it's a package validation.

When running your package on CI (appveyor, travis or any other) we could run Conan to create the package and check. But prepare a full environment with compiler, build-essential , conan and all stuff could be boring, so we use Docker. Conan provides a good range of images, including gcc and clang. Here I added only GCC 8 because we only need to create a package for any architecture or OS -- header-only project doesn't provide binaries by platform.

### How to upload?

Conan uses Bintray to store their packages. You need to create an account on bintray for that. There is a good documentation how to create a bintray account [here](https://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html).

The build.py is configured following the reference *skypjack/conan/uvw/<version>*. Where:
- skypjack is your Bintray user name
- conan is the repository name
- uvw is the package name

Both username and repository you will need to set manually on web interface. Both username and repository could be changed by your preference, I just followed the convention.

Also, build.py has a rule to upload only tags or any branch with the pattern name "v\d+\.\d+\.\d+.*".

And finally, you must set the variable **CONAN_PASSWORD** on Travis settings. The password is the Bintray API Key, not your account password. To read your API key you need to access *https://bintray.com/profile/edit* and click on API Key button. Don't forget to mark as secret on Travis settings. 

After to upload your package by CI, we recommend update the Bintray package page:
*https://bintray.com/skypjack/conan/uvw%3Askypjack/edit?tab=general*
The page contains only project metadata, as url, maturity (official), license -- There is a field for package avatar, you could use conan-uvw logo with you prefer or uvw official. 

Okay, this is a lot of information. Please, feel free to ask anything.

I included @danimtb to review this PR. He is a Conan expert and maintainer.

Regards!

/cc @danimtb

closes #135

### CODE REVIEW

**Comment by uilianries** [comment]
Conan log on Travis CI: https://travis-ci.org/uilianries/uvw/jobs/444613849

**Comment by skypjack** [comment]
Hi!

It seems I've quite a lot of stuff to read.  
I think I'll have the time to work on it tomorrow or the day after tomorrow.

Thank you a lot for your efforts, really appreciated.  
I'll do my best to give you a feedback as soon as possible!

**Comment by uilianries** [comment]
> My only concern is that this will create and upload a new package for every commit if am not missing something.

Sorry, I forgot to apply the filter. I just updated it now, thanks.

> Maybe the Conan CI part should only be fired only on a new TAG

The only problem is broken jobs during new release. We will need fix the job or recipe and the author re-create the tag.

**Comment by skypjack** [comment]
Ok, account and travis are set. What about if I merge your work on a dedicated branch and create a tag there to test it, before to merge everything on `master`?

**Comment by uilianries** [comment]
Sure! build.py will upload any branch named as *v?<number>.<number>.<number><anything>*. So you could create the branch **v1.11.2_conan**.

I checked your Bintray repo, it looks good.

**Comment by skypjack** [comment]
[Done](https://travis-ci.org/skypjack/uvw/jobs/446027475). Not sure everything worked as expected actually.
I'm not yet much confident with conan. If you can confirm it, I'll merge everything on `master` and create a dedicated tag there to track the changes.

Thank you!!

**Comment by uilianries** [comment]
It's alive! All working good!

Reading some details on the log:

At the line [578](https://travis-ci.org/skypjack/uvw/jobs/446027475#L578) our python script detected the branch name as *v1.11.2_conan*

On the next step, line [581](https://travis-ci.org/skypjack/uvw/jobs/446027475#L581), it matched your branch name with the regex pattern *'v?\d+\.\d+\.\d+.*'*. Once matched, package channel is named as **stable** automatically.

Your login was verified with success at the line [616](https://travis-ci.org/skypjack/uvw/jobs/446027475#L616).

All tests and build are executed into a docker container by the image *conanio/gcc8*. It's listed at line [629](https://travis-ci.org/skypjack/uvw/jobs/446027475#L629). That image is based on ubuntu 18.04 + gcc 8.2 + python 2 + conan

Your package is created at the line [854](https://travis-ci.org/skypjack/uvw/jobs/446027475#L854) and tested at [928](https://travis-ci.org/skypjack/uvw/jobs/446027475#L928).

The upload starts at [990](https://travis-ci.org/skypjack/uvw/jobs/446027475#L990).

All looks good in your bintray page:

bintray

Now you could merge into master and request the Conan Center inclusion.

Conan center is a promotion to get your package distributed as official in Conan channel. Otherwise, people will need to add your bintray repository directly.
To request that inclusion, just click on the mug icon. There is screenshot [here](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries) as example.

If you are interested, I could open a new PR including some info about how to use Conan in your README file.

Regards!

**Comment by skypjack** [comment]
Badge links [were broken](https://github.com/skypjack/uvw/commit/8f7014af4e137a61970c7e7c19fd4354ea61b0f6). Fixed.  
It's ready to merge now. :+1:

**Comment by uilianries** [comment]
> I don't know what it means to use Conan in a README file, so I cannot promise I'll accept it, but it would be welcome in any case!! :-)

I would like to add a **package** section on readme file, explaining how to create and install conan package for uvw. Also, it could be update with vcpkg info

> Badge links were broken. Fixed. 

Thanks!

> Just out of curiosity, what's the difference between the stuff you added to the repository and what happens with the import from github link from my account?
The latter looks far easier to do and it seems there is nothing to add to the repo, so I was wondering what are the cons of that.

They are different strategies.

When you have both the conan recipe and your project in same repo, you're in the control. All the necessary things are downloaded at once. It's centralized, easier to maintain. Also, you don't need to update the recipe for each new release.

When we need to create a Conan recipe for a project that dont care about packaging or dont want mix both code and tools stuff, we create a separated repository that imports the project by git or by any other. But we need to update the recipe version for each new release. The advantage is that we have more freedom by changing the repository, files and CI without affecting the code.

Some projects, like Poco, opted by keeping a second repository: https://github.com/pocoproject/conan-poco. Poco is a huge project and have a complex matrix to be built on CI.

As your project is header-only and you are interested in package tools, I think keep both on same repo is the better strategy. Also, we have an experimental feature for [SCM](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm-experimental). I'll open a new PR when SCM becomes official and stable.

**Comment by skypjack** [comment]
>I would like to add a package section on readme file, explaining how to create and install conan package for uvw. Also, it could be update with vcpkg info

Yeah, I did [something similar](https://github.com/skypjack/entt#packaging-tools) in the README of `EnTT`. If you want to open a PR, I can proceed as I did for this one, that is I can merge it on a branch, add also a note for `vcpkg` and then squash everything on `master` at once.

>They are different strategies. [...] I'll open a new PR when SCM becomes official and stable.

Thanks for the time you spent to give me all the details. Really, really appreciated. I'm just curious to know how things work under the hood and therefore I'm used to ask. It's a pleasure when I find someone willing to explain. :smile: :+1:

**Comment by skypjack** [comment]
Uhm... not sure [this](https://bintray.com/skypjack/conan) is the expected behavior.
It created another project from the tag on master, this time called `uvw:skypjack`.

**Comment by uilianries** [comment]
Yes, bintray uses <project>:<author> I checked now.

You could remove remove the uploaded package, rename the created before and restart Travis CI job,

OR,

Remove the package created before and update the new one.

sorry for my misunderstanding

**Comment by skypjack** [comment]
Oh, my fault, I didn't get it. I'm sorry. Thanks for your reply.

**Comment by uilianries** [comment]
Just dont forget to ask for Conan center inclusion!

Cheers!

**Comment by skypjack** [comment]
Good point. Done.

**Pull request merged**
