### PR TITLE
Add a TCP::connect overload for addrinfo structs

### PR DESCRIPTION
**Pull request by eklitzke**
This is my proposed solution to #102 .

### CODE REVIEW

**Comment by skypjack** [comment]
I'm out of home until Sunday. I'll look into the PR next week probably.  
I'm sorry for the inconvenience.

**Comment by eklitzke** [comment]
No worries, take your time.

**Comment by skypjack** [comment]
I wouldn't do that probably. You don't need to pull in another function template actually.  
We can rework it introducing a new `connect` that accepts an already erased addr type. The other `connect` around can just `reinterpret_cast` it before to push the parameter to the new function.

Would it work for you?

**Comment by eklitzke** [comment]
That sounds good to me.

**Pull request closed without merging**
