### PR TITLE
Fix typo in UDP documentation

### PR DESCRIPTION
**Pull request by fcelda**

### CODE REVIEW

**Comment by skypjack** [comment]
Good catch. Thank you very much.

**Comment by fcelda** [comment]
No problem. We just started using uvw for a project and we are really happy with it. So I hope more contributions will come (other than fixing a doc).

**Comment by skypjack** [comment]
Wow. Awesome. Feel free to write me if you have any suggestion or request for improvements and new features. Contributions are welcome!!

**Comment by skypjack** [comment]
@fcelda I added to the README file a section that contains a list of projects that use `uvw`. I'd like to add your project to the list if possible. Feel free to create a PR for that if you are interested. Thank you.

**Pull request merged**
