### PR TITLE
CMake updates

### PR DESCRIPTION
**Pull request by tusharpm**
CMake is a supported build system for libuv since version 1.21.
That can be leveraged to simplify the uvw test build.

Includes an optimisation to reduce one CMake invocation for fetching dependencies.
Note: for local builds the `deps` directory should be cleaned up first (`git clean -ffdx deps`).

### CODE REVIEW

**Comment by skypjack** [comment]
It would be great, but something failed. Can you look into the problem?

**Comment by tusharpm** [comment]
It had failed in one of the libuv tests, [time precision of uv_sleep](https://github.com/libuv/libuv/blob/v1.22.0/test/test-hrtime.c#L50).

I disabled running the tests for the dependencies.

**Comment by skypjack** [comment]
Oh, sorry, I'm at the beach with my son, I didn't see what failed. Forgive me.

**Comment by skypjack** [comment]
Thank as usual.

**Pull request merged**
