### PR TITLE
FEATURE: expose write_queue_size

### PR DESCRIPTION
**Pull request by bmagistro**
There may be a better way to access member variables from the underlying libuv types but I'm not sure how to do it.

### CODE REVIEW

**Comment by skypjack** [comment]
Do you mean `size_t uv_stream_get_write_queue_size(const uv_stream_t* stream)`?

Moreover, the method you defined doesn't follow the naming convention of the whole project.
I can't accept it as it is, I'm sorry.

**Comment by bmagistro** [comment]
I am not sure what you are referring to.  In this case I am referring to `uv_stream_t.write_queue_size` as defined here http://docs.libuv.org/en/v1.x/stream.html.  I can easily rename the function to be `writeQueueSize()`.

**Comment by skypjack** [comment]
`uv_stream_get_write_queue_size` is a new method introduced with libuv 1.19 to get that parameter in a _safe_ way.

**Comment by bmagistro** [comment]
Huh, thanks for pointing that out.  Now I'm not sure I ever scrolled down to the bottom of the page (or I've just been missing it).  I will update to use this method and update name accrodingly.

**Comment by skypjack** [comment]
You're welcome.
I'd name it with a shorter name probably, something like `queue` and that's all. I don't see neither a `read_queue_size` nor anything else on `libuv`, so being that explicit and redundant is probably useless. My two cents.

**Comment by bmagistro** [comment]
So I did a little looking to see what else might be new in the parts I'm using.  In UDP there are `send_queue_count` and `send_queue_size`, so went with the name mentioned above.

**Comment by skypjack** [comment]
Can you add also the other functions from UDP in the PR?

**Comment by bmagistro** [comment]
Functions added, guess I forgot to hit comment the other day.

**Comment by skypjack** [comment]
Yeah, I saw the commit. I have to add a few testsbefore to merge it but I've been busy today and I didn't do that. I'm sorry.
Hopefully tomorrow, otherwise I'll tackle it in during the weekend. ;-)

**Pull request merged**
