### PR TITLE
Migrate the project from C++14 to C++11.

### PR DESCRIPTION
**Pull request by ZgblKylin**
All tests passed.

### CODE REVIEW

**Comment by skypjack** [comment]
Thanks for your effort, really appreciated. I can create a dedicated branch fro C++11, but `master` will keep going on with C++14.  
That being said, here it is the results from the CI:

>All checks have failed

I cannot really merge the PR as it stands. I'm sorry. Can you review it?

**Comment by ZgblKylin** [comment]
No more changes or features added, just done the migration because our build environment only supports c++11, and this projects seems run well without c++14



 
From: Michele Caini
Date: 2018-11-03 20:21
To: skypjack/uvw
CC: Fei Chong; Mention
Subject: Re: [skypjack/uvw] Migrate the project from C++14 to C++11. (#138)
@ZgblKylin Any news on this?

**Comment by skypjack** [comment]
Yeah, I see, but this PR fails to compile with the CI against all the compilers. Can you fix it?

**Comment by ZgblKylin** [comment]
That seems strange. I've built and run tests on my computer, passed on gcc/msvc, I'll try again on the CI.

**Comment by skypjack** [comment]
> That seems strange. I've built and run tests on my computer, passed on gcc/msvc, I'll try again on the CI.

Thanks. [Here](https://travis-ci.org/skypjack/uvw/builds/449280515?utm_source=github_status&utm_medium=notification) you've the report. As you can see, all the jobs failed, but the one of conan that just skipped because there are no new tags.

**Comment by ZgblKylin** [comment]
Yes, was checking C++14 remaining by static analyze tools, fixed main.cpp, and update sample code in README.md

**Comment by skypjack** [comment]
Good. It seems everything works fine now. Thank you very much.  
As soon as I've some free time, I'll create a dedicated branch to host the C++11 version of `uvw` for those interested in it.  
`master` will still use more recent revisions of the standard (I'm porting `uvw` to C++17 actually).  
Are you an active user of the library? Would you be interested to help me to keep up-to-date the C++11 branch?

**Comment by ZgblKylin** [comment]
Yes, my team's using libuv/uvw in our projects.
It's the basis layer of our component, so I'll be working on keeping it up-to-date.
I think the C++11 branch could provide compatibility for those scenarios using limited building environment, and master will keep track of the newest standard.



 
From: Michele Caini
Date: 2018-11-04 07:00
To: skypjack/uvw
CC: Fei Chong; Mention
Subject: Re: [skypjack/uvw] Migrate the project from C++14 to C++11. (#138)
Good. It seems everything works fine now. Thank you very much.
As soon as I've some free time, I'll create a dedicated branch to host the C++11 version of uvw for those interested in it.
master will still use more recent revisions of the standard (I'm porting uvw to C++17 actually).
Are you an active user of the library? Would you be interested to help me to keep up-to-date the C++11 branch?

**Comment by ZgblKylin** [comment]
We're developing a plugin-based framework using Qt, but Qt's network module is using Select, which behave badly in high concurrency or high data rate. So we need another solution using iocp/epoll.
Compared with ASIO, libuv is more concise and elegant, the only problem is it's written in C -- Managing resouces explicitly is a bad idea, so we found uvw instead.
 


 
From: Michele Caini
Date: 2018-11-05 18:27
To: skypjack/uvw
CC: Fei Chong; Mention
Subject: Re: [skypjack/uvw] Migrate the project from C++14 to C++11. (#138)
Yes, my team's using libuv/uvw in our projects. [...] It's the basis layer of our component, so I'll be working on keeping it up-to-date.
It sounds good. Can you tell me more about your projects/team and how do you use uvw?
It's interesting to know how it's used in real world software. Just out curiosity anyway.
I think the C++11 branch could provide compatibility for those scenarios using limited building environment, and master will keep track of the newest standard.
Indeed. I'll continue to work on master and I'll let the cpp11 branch be supported by the community, as long as someone is willing to contribute, because unfortunately I have no way to carry on both of them at the moment. I'm sorry.
Please, consider also supporting uvw if it's possible. It would help to continue the development.
Keep in mind that it's in maintenance mode at the moment, because of a lack of time and resources my side to continue the development.
That being said, thank you so much for your PR. Really appreciated. ???? ????

**Pull request merged**
