### PR TITLE
Cross-platform support to shared libs

### LINKED ISSUE #196: BUILD_UVW_LIBS doesn't work on Windows (no symbols are exported)
Hi,

When building UVW as a shared library (by setting BUILD_UVW_LIBS to ON) on Windows, a DLL is created but without any .lib file.
The issue is that nothing is exported using__declspec(dllexport).

I suggest to make the same thing as libuv, that is:
https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/include/uv.h#L30

And putting the equivalent of UV_EXTERN to classes and functions.
This would allow to use -fvisibility=hidden with gcc too.

Are you willing to support that ?

Thanks :)

### PR DESCRIPTION
**Pull request by stefanofiorentino**
closes #196

### CODE REVIEW

**Comment by stefanofiorentino** [comment]
This is intended for comparing against the current HEAD.
NOTE: still contains minor flaws about FakeEvent/Emitter test classses.

**Comment by stefanofiorentino** [comment]
@skypjack this is the best solution I can find to have cross-platform support to shared libs. 
In my opinion the question rose by @amurzeau is right, do we want to fully support shared libs too?
From my point of view, the price is simplicity and readability.

**Comment by skypjack** [comment]
>From my point of view, the price is simplicity and readability.

Do you mean not supporting them? Because this change isn't exactly simple nor easy to read. :smile:

**Comment by stefanofiorentino** [comment]
I mean we can support only static linking (not the shared one).
The simplicity and readability will be impacted a lot by this mod.

**Comment by skypjack** [comment]
>The simplicity and readability will be impacted a lot by this mod.

Indeed, it doesn't seem to be something simple to maintain.

**Comment by stefanofiorentino** [comment]
I'll close this as per discussion.

**Pull request closed without merging**
