### PR TITLE
Adding tokens to write events.

### PR DESCRIPTION
**Pull request by nicolasnoble**
This addresses one part of #203.

### CODE REVIEW

**Comment by nicolasnoble** [comment]
This still needs the multiple buffers code.

**Comment by skypjack** [comment]
Also, `std::uintptr_t` isn't that portable. I'd rather get rid of it to avoid portability issues.

**Comment by skypjack** [comment]
Moreover, I don't see exactly what the role of the _token_ is.
If all you need is to get a write request along with the write event, the former can be attached to the latter. Since handles in`uvw` emit _on themselves_, you're also guaranteed that a given request is what you expect it to be in a callback and not one randomly received from another handle.

**Comment by nicolasnoble** [comment]
> If all you need is to get a write request along with the write event, the former can be attached to the latter.

That's basically what this is, yes. This tentatively hides the concept of write request out to the user, because that's the only need there can be for them. Getting a `WriteReq` might be more confusing, but that's okay too, since that's what libuv actually does. I'm fine either way personally.

> Since handles in`uvw` emit _on themselves_, you're also guaranteed that a given request is what you expect it to be in a callback and not one randomly received from another handle.

Which is fine when you're only have one outstanding write for a simple protocol, but if you have a multiplexing protocol with substreams, such as the likes of http/2, then you need a multiplexing/demultiplexing layer that lets you know which substream got its event fired. This is a solution for this. You can then very easily write something along this pseudo-c++:

```C
class Http2 {
  std::map<uvw::StreamHandle::TokenType, http2::SubStream*> m_outstandingWrites;

  void initEvents() {
    m_tcp->on<uvw::WriteEvent>([this](const uvw::WriteEvent &event, uvw::TCPHandle &) {
      m_outstandingWrites[event.token]->publish(Http2WriteEvent{});
      m_outstandingWrites.erase(event.token);
    }
  }
  uvw::TCPHandle m_tcp;

  class SubStream : public Publisher {
    void write(const Payload &payload) {
      auto token = m_parent->m_tcp->write(payload.bytes(), payload.length());
      m_outstandingWrites.insert(token, this);      
    }
  };
};
```

**Comment by nicolasnoble** [comment]
And the more I'm thinking about it, the more I realize this isn't even going far enough. Closing this one and updating the associated bug.

**Pull request closed without merging**
